from __future__ import annotations

from pspdisasm.model import (
    DisassemblyResult,
    ExecutableModel,
    FunctionRecord,
    LibraryExport,
    LibraryImport,
    ModuleInfo,
    NidEntry,
    NidSymbol,
)
from pspdisasm.nids import NidDatabase


def _module(name: str, *, imports=None, exports=None) -> ExecutableModel:
    return ExecutableModel(
        source_name=f"{name}.prx",
        input_kind="elf",
        executable_kind="prx",
        needs_decryption=False,
        module_info=ModuleInfo(
            attributes=0,
            version=(1, 0),
            name=name,
            gp_value=0,
            exports_start=0,
            exports_end=0,
            imports_start=0,
            imports_end=0,
            address=0,
            location="test",
        ),
        imports=imports or [],
        exports=exports or [],
    )


def _import(library: str, nid: int, address: int, kind: str = "function"):
    entry = NidEntry(nid=nid, address=address, kind=kind, nid_address=address - 4)
    return LibraryImport(
        name=library,
        flags=0,
        entry_length=5,
        function_count=1 if kind == "function" else 0,
        variable_count=1 if kind == "variable" else 0,
        address=address - 0x20,
        functions=[entry] if kind == "function" else [],
        variables=[entry] if kind == "variable" else [],
    )


def _export(library: str, nid: int, address: int, kind: str = "function"):
    entry = NidEntry(nid=nid, address=address, kind=kind, nid_address=address - 4)
    return LibraryExport(
        name=library,
        flags=0,
        entry_length=4,
        function_count=1 if kind == "function" else 0,
        variable_count=1 if kind == "variable" else 0,
        address=address - 0x20,
        functions=[entry] if kind == "function" else [],
        variables=[entry] if kind == "variable" else [],
    )


def _function(name: str, address: int) -> FunctionRecord:
    return FunctionRecord(
        name=name,
        address=address,
        size=8,
        section=".text",
        assembly="",
        instruction_count=0,
    )


def test_database_name_resolves_both_sides_and_unique_modules_link() -> None:
    from pspdisasm.linker import ModuleAnalysisInput, link_modules

    nid = 0xAABBCCDD
    importer = _module("Game", imports=[_import("TestLib", nid, 0x08801000)])
    exporter = _module("Service", exports=[_export("TestLib", nid, 0x08902000)])
    database = NidDatabase()
    database.add(NidSymbol("TestLib", nid, "sceTestDoThing", "function", "synthetic-db"))

    result = link_modules(
        [ModuleAnalysisInput(importer), ModuleAnalysisInput(exporter)],
        database,
    )

    assert result.modules == ["Game", "Service"]
    assert len(result.links) == 1
    link = result.links[0]
    assert link.importing_module == "Game"
    assert link.exporting_module == "Service"
    assert link.library == "TestLib"
    assert link.nid == nid
    assert link.name == "sceTestDoThing"
    assert link.import_address == 0x08801000
    assert link.export_address == 0x08902000

    assert {(item.module, item.direction, item.name, item.source) for item in result.resolutions} == {
        ("Game", "import", "sceTestDoThing", "synthetic-db"),
        ("Service", "export", "sceTestDoThing", "synthetic-db"),
    }
    proposals = {(item.module, item.address): item for item in result.propagated_symbols}
    assert proposals[("Game", 0x08801000)].name == "sceTestDoThing"
    assert proposals[("Game", 0x08801000)].confidence == 1.0
    assert proposals[("Service", 0x08902000)].confidence == 1.0


def test_unique_link_propagates_meaningful_exporter_function_name_without_database() -> None:
    from pspdisasm.linker import ModuleAnalysisInput, link_modules

    nid = 0x11223344
    importer = _module("Game", imports=[_import("GameService", nid, 0x08801100)])
    exporter = _module("Service", exports=[_export("GameService", nid, 0x08903000)])
    exporter_disassembly = DisassemblyResult(
        source_name="Service.prx",
        functions=[_function("GameService_DoThing", 0x08903000)],
    )

    result = link_modules(
        [
            ModuleAnalysisInput(importer),
            ModuleAnalysisInput(exporter, exporter_disassembly),
        ]
    )

    assert result.links[0].name == "GameService_DoThing"
    assert result.links[0].name_source == "module:Service"
    proposals = {(item.module, item.address): item for item in result.propagated_symbols}
    assert proposals[("Game", 0x08801100)].name == "GameService_DoThing"
    assert proposals[("Game", 0x08801100)].confidence == 0.95


def test_autogenerated_export_name_is_not_propagated_as_strong() -> None:
    from pspdisasm.linker import ModuleAnalysisInput, link_modules

    nid = 0x55667788
    importer = _module("Game", imports=[_import("UnknownLib", nid, 0x08801200)])
    exporter = _module("Service", exports=[_export("UnknownLib", nid, 0x08904000)])
    exporter_disassembly = DisassemblyResult(
        source_name="Service.prx",
        functions=[_function("func_08904000", 0x08904000)],
    )

    result = link_modules(
        [ModuleAnalysisInput(importer), ModuleAnalysisInput(exporter, exporter_disassembly)]
    )

    assert result.links[0].name == "UnknownLib_55667788"
    proposals = {(item.module, item.address): item for item in result.propagated_symbols}
    assert proposals[("Game", 0x08801200)].name == "UnknownLib_55667788"
    assert proposals[("Game", 0x08801200)].confidence == 0.5


def test_ambiguous_exporters_do_not_create_a_link() -> None:
    from pspdisasm.linker import ModuleAnalysisInput, link_modules

    nid = 0xDEADBEEF
    importer = _module("Game", imports=[_import("SharedLib", nid, 0x08801300)])
    exporter_a = _module("ServiceA", exports=[_export("SharedLib", nid, 0x08905000)])
    exporter_b = _module("ServiceB", exports=[_export("SharedLib", nid, 0x08A06000)])

    result = link_modules(
        [
            ModuleAnalysisInput(importer),
            ModuleAnalysisInput(exporter_a),
            ModuleAnalysisInput(exporter_b),
        ]
    )

    assert result.links == []
    assert len(result.warnings) == 1
    assert "ambiguous" in result.warnings[0].lower()
    assert "ServiceA" in result.warnings[0]
    assert "ServiceB" in result.warnings[0]


def test_import_and_export_kinds_must_match() -> None:
    from pspdisasm.linker import ModuleAnalysisInput, link_modules

    nid = 0x01020304
    importer = _module("Game", imports=[_import("Kinds", nid, 0x08801400, "variable")])
    exporter = _module("Service", exports=[_export("Kinds", nid, 0x08907000, "function")])

    result = link_modules([ModuleAnalysisInput(importer), ModuleAnalysisInput(exporter)])

    assert result.links == []
