from __future__ import annotations

import json
from pathlib import Path

import pspdisasm
from pspdisasm.model import DataTypeRecord, DataTypingResult, DisassemblyResult, SymbolRecord
from pspdisasm.project import _render_symbols, generate_project
from tests.fixtures import build_allegrex_elf32


def test_project_writes_all_phase6c_metadata_files(tmp_path: Path):
    source = tmp_path / "sample.elf"
    output = tmp_path / "project"
    source.write_bytes(build_allegrex_elf32())

    generate_project(source, output)

    expected = {
        "metadata/data_typing.json",
        "metadata/data_types.json",
        "metadata/typed_references.json",
        "metadata/typed_callgraph.json",
    }
    for relative in expected:
        assert (output / relative).exists(), relative

    complete = json.loads((output / "metadata" / "data_typing.json").read_text(encoding="utf-8"))
    data_types = json.loads((output / "metadata" / "data_types.json").read_text(encoding="utf-8"))
    typed_references = json.loads((output / "metadata" / "typed_references.json").read_text(encoding="utf-8"))
    typed_callgraph = json.loads((output / "metadata" / "typed_callgraph.json").read_text(encoding="utf-8"))

    assert complete["data_types"] == data_types
    assert complete["typed_references"] == typed_references
    assert complete["call_edges"] == typed_callgraph
    assert any(record["type_name"] == "string" and record["address"] == 0x08800100 for record in data_types)


def test_type_generated_symbols_replace_only_weak_autogenerated_data_names():
    result = DisassemblyResult(
        source_name="fixture.elf",
        symbols=[
            SymbolRecord("D_00002000", 0x2000, ".data", "data", "auto"),
            SymbolRecord("CuratedTable", 0x2010, ".data", "data", "user"),
        ],
    )
    typing = DataTypingResult(
        source_name="fixture.elf",
        data_types=[
            DataTypeRecord(0x2000, ".data", "pointer_table", 12, count=3, element_type="pointer", element_size=4, confidence=0.95),
            DataTypeRecord(0x2010, ".data", "function_pointer_table", 8, count=2, element_type="function_pointer", element_size=4, confidence=0.95),
            DataTypeRecord(0x2020, ".data", "function_pointer", 4, target_address=0x1000, confidence=0.95),
            DataTypeRecord(0x2030, ".data", "struct_candidate", 16, confidence=0.80),
        ],
    )

    symbols = _render_symbols(0, result, (), typing.data_types)

    assert "PTRTBL_00002000 = 0x00002000;" in symbols
    assert "CuratedTable = 0x00002010;" in symbols
    assert "FUNCPTRTBL_00002010" not in symbols
    assert "FUNCPTR_00002020 = 0x00002020;" in symbols
    assert "00002030" not in symbols


def test_phase6c_public_api_remains_available_after_later_phases():
    assert callable(pspdisasm.analyze_data_types)
    assert pspdisasm.__version__ == "0.10.0"
