from __future__ import annotations

from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
import re
from typing import Iterable

from .model import (
    DisassemblyResult,
    ExecutableModel,
    ModuleLink,
    ModuleLinkAnalysis,
    NidEntry,
    NidResolution,
    PropagatedSymbol,
)
from .nids import NidDatabase, is_placeholder_name


@dataclass(slots=True)
class ModuleAnalysisInput:
    model: ExecutableModel
    disassembly: DisassemblyResult | None = None


def _module_name(model: ExecutableModel) -> str:
    if model.module_info is not None and model.module_info.name.strip():
        return model.module_info.name.strip()
    stem = Path(model.source_name).stem
    return stem or model.source_name


def _module_labels(units: list[ModuleAnalysisInput]) -> tuple[list[str], list[str]]:
    raw_names = [_module_name(unit.model) for unit in units]
    counts = Counter(raw_names)
    candidate_counts: dict[str, int] = defaultdict(int)
    duplicate_labels: dict[str, list[str]] = defaultdict(list)
    labels: list[str] = []

    for unit, raw_name in zip(units, raw_names):
        if counts[raw_name] == 1:
            labels.append(raw_name)
            continue

        source_name = Path(unit.model.source_name).name or "module"
        base_label = f"{raw_name}@{source_name}"
        candidate_counts[base_label] += 1
        ordinal = candidate_counts[base_label]
        label = base_label if ordinal == 1 else f"{base_label}#{ordinal}"
        labels.append(label)
        duplicate_labels[raw_name].append(label)

    warnings = [
        f"Duplicate module name {raw_name!r} disambiguated by source file: {', '.join(names)}"
        for raw_name, names in sorted(duplicate_labels.items())
    ]
    return labels, warnings


def _iter_entries(model: ExecutableModel, direction: str):
    libraries = model.imports if direction == "import" else model.exports
    for library in libraries:
        for entry in library.functions:
            yield library.name, "function", entry
        for entry in library.variables:
            yield library.name, "variable", entry


def _fallback_name(library: str, nid: int) -> str:
    return f"{library}_{nid:08X}"


def _resolution(
    module: str,
    library: str,
    kind: str,
    entry: NidEntry,
    direction: str,
    database: NidDatabase,
) -> NidResolution:
    symbol = database.resolve(library, entry.nid, kind)
    if symbol is None:
        name = _fallback_name(library, entry.nid)
        source = "unresolved"
    else:
        name = symbol.name
        source = symbol.source
    return NidResolution(
        module=module,
        library=library,
        nid=entry.nid,
        name=name,
        kind=kind,
        address=entry.address,
        direction=direction,
        source=source,
    )


def _is_strong_resolution(resolution: NidResolution) -> bool:
    return resolution.source != "unresolved" and not is_placeholder_name(
        resolution.library,
        resolution.nid,
        resolution.name,
    )


def _is_autogenerated_name(name: str) -> bool:
    value = name.strip()
    patterns = (
        r"func_[0-9A-Fa-f]+",
        r"D_[0-9A-Fa-f]+",
        r"L[0-9A-Fa-f]+",
        r"label_[0-9A-Fa-f]+",
        r"jtbl_[0-9A-Fa-f]+",
    )
    return any(re.fullmatch(pattern, value) for pattern in patterns)


def _local_name(unit: ModuleAnalysisInput, kind: str, address: int) -> str | None:
    disassembly = unit.disassembly
    if disassembly is None:
        return None
    if kind == "function":
        for function in disassembly.functions:
            if function.address == address and not _is_autogenerated_name(function.name):
                return function.name
    for symbol in disassembly.symbols:
        if symbol.address != address:
            continue
        if symbol.kind in {"label", "branchlabel"}:
            continue
        if not _is_autogenerated_name(symbol.name):
            return symbol.name
    return None


def _proposal_from_resolution(resolution: NidResolution) -> PropagatedSymbol:
    strong = _is_strong_resolution(resolution)
    return PropagatedSymbol(
        module=resolution.module,
        address=resolution.address,
        name=resolution.name,
        kind=resolution.kind,
        library=resolution.library,
        nid=resolution.nid,
        source=resolution.source,
        confidence=1.0 if strong else 0.5,
    )


def _deduplicate_proposals(records: Iterable[PropagatedSymbol]) -> list[PropagatedSymbol]:
    selected: dict[tuple[str, int], PropagatedSymbol] = {}
    for record in records:
        key = (record.module, record.address)
        current = selected.get(key)
        if current is None:
            selected[key] = record
            continue
        if record.confidence > current.confidence:
            selected[key] = record
            continue
        if record.confidence == current.confidence and (
            record.name,
            record.source,
            record.library,
            record.nid,
        ) < (
            current.name,
            current.source,
            current.library,
            current.nid,
        ):
            selected[key] = record
    return sorted(selected.values(), key=lambda item: (item.module, item.address, item.name))


def link_modules(
    modules: Iterable[ModuleAnalysisInput],
    database: NidDatabase | None = None,
) -> ModuleLinkAnalysis:
    units = list(modules)
    database = database or NidDatabase()
    module_labels, identity_warnings = _module_labels(units)
    warnings = [*database.warnings, *identity_warnings]

    resolutions: list[NidResolution] = []
    resolution_by_identity: dict[tuple[int, str, str, int, int], NidResolution] = {}
    proposals: list[PropagatedSymbol] = []

    exporters: dict[
        tuple[str, str, int],
        list[tuple[int, ModuleAnalysisInput, str, NidEntry]],
    ] = {}
    for unit_index, (unit, module_label) in enumerate(zip(units, module_labels)):
        for direction in ("import", "export"):
            for library, kind, entry in _iter_entries(unit.model, direction):
                resolution = _resolution(module_label, library, kind, entry, direction, database)
                resolutions.append(resolution)
                resolution_by_identity[
                    (unit_index, direction, library, entry.nid, entry.address)
                ] = resolution
                proposals.append(_proposal_from_resolution(resolution))
                if direction == "export":
                    exporters.setdefault((library, kind, entry.nid), []).append(
                        (unit_index, unit, module_label, entry)
                    )

    links: list[ModuleLink] = []
    for importing_index, (unit, importing_module) in enumerate(zip(units, module_labels)):
        for library, kind, entry in _iter_entries(unit.model, "import"):
            candidates = [
                candidate
                for candidate in exporters.get((library, kind, entry.nid), [])
                if candidate[0] != importing_index
            ]
            if not candidates:
                continue
            if len(candidates) > 1:
                providers = sorted(candidate[2] for candidate in candidates)
                warnings.append(
                    f"Ambiguous export for {importing_module} import "
                    f"{library}/{kind}/0x{entry.nid:08X}: {', '.join(providers)}"
                )
                continue

            exporter_index, exporter_unit, exporting_module, export_entry = candidates[0]
            import_resolution = resolution_by_identity[
                (importing_index, "import", library, entry.nid, entry.address)
            ]
            export_resolution = resolution_by_identity[
                (exporter_index, "export", library, export_entry.nid, export_entry.address)
            ]

            name = _fallback_name(library, entry.nid)
            name_source = "unresolved"
            if _is_strong_resolution(import_resolution):
                name = import_resolution.name
                name_source = import_resolution.source
            elif _is_strong_resolution(export_resolution):
                name = export_resolution.name
                name_source = export_resolution.source
            else:
                local_name = _local_name(exporter_unit, kind, export_entry.address)
                if local_name is not None:
                    name = local_name
                    name_source = f"module:{exporting_module}"

            links.append(
                ModuleLink(
                    importing_module=importing_module,
                    exporting_module=exporting_module,
                    library=library,
                    nid=entry.nid,
                    name=name,
                    kind=kind,
                    import_address=entry.address,
                    export_address=export_entry.address,
                    name_source=name_source,
                )
            )

            if name_source.startswith("module:"):
                proposals.append(
                    PropagatedSymbol(
                        module=importing_module,
                        address=entry.address,
                        name=name,
                        kind=kind,
                        library=library,
                        nid=entry.nid,
                        source=name_source,
                        confidence=0.95,
                    )
                )

    return ModuleLinkAnalysis(
        modules=module_labels,
        resolutions=sorted(
            resolutions,
            key=lambda item: (
                item.module,
                item.direction,
                item.library,
                item.kind,
                item.nid,
                item.address,
            ),
        ),
        links=sorted(
            links,
            key=lambda item: (
                item.importing_module,
                item.exporting_module,
                item.library,
                item.kind,
                item.nid,
                item.import_address,
            ),
        ),
        propagated_symbols=_deduplicate_proposals(proposals),
        warnings=warnings,
    )
